"""Generate the vLLM experiment matrix from the scenario library.

The matrix is derived rather than hand-written so it cannot drift from the
scenario definitions it describes. `experiments/experiment_matrix.yaml` (the
Boutique one) was maintained by hand and did drift — it specifies an
`injector:` field that the batch runner silently ignores.

    python -m rca_engine.scripts.gen_vllm_matrix
    python -m rca_engine.scripts.gen_vllm_matrix --check   # CI: fail if stale
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

from workload.scenarios import scenarios_for

DEFAULT_OUT = Path("experiments/vllm_matrix.yaml")

#: Repeats per scenario. Five is enough to see whether a miss is systematic
#: rather than noise, without pushing the capture session past a working day.
REPEATS = 5
#: The clean control needs more samples: a false-positive rate estimated from
#: five runs has a confidence interval too wide to claim anything.
CLEAN_REPEATS = 8

BASELINE_S = 120
FAULT_S = 180
SETTLE_S = 60


def render() -> str:
    scenarios = scenarios_for()
    per_run = BASELINE_S + FAULT_S + SETTLE_S
    total = sum(
        CLEAN_REPEATS if s.name == "clean" else REPEATS for s in scenarios
    )

    lines = [
        "# vLLM TTFT experiment matrix.",
        "#",
        "# GENERATED by rca_engine/scripts/gen_vllm_matrix.py from",
        "# workload/scenarios.py. Edit the scenario library, not this file.",
        "#",
        f"# {len(scenarios)} scenarios, {REPEATS} repeats each ({CLEAN_REPEATS} for the",
        "# clean control, since a false-positive rate needs more samples than",
        "# top-1 accuracy does).",
        "#",
        f"# Total: {total} runs x ~{per_run}s = ~{total * per_run / 3600:.1f}h",
        "",
        "defaults:",
        f"  baseline_seconds: {BASELINE_S}",
        f"  fault_seconds: {FAULT_S}",
        f"  settle_seconds: {SETTLE_S}",
        "  domain: vllm",
        "",
        "experiments:",
    ]

    for scenario in scenarios:
        repeats = CLEAN_REPEATS if scenario.name == "clean" else REPEATS
        lines += [
            f"  - scenario: {scenario.name}",
            f"    kind: {scenario.kind}",
            f"    repeats: {repeats}",
            f"    root_cause: {scenario.ground_truth or 'null'}",
            f"    expect_verdict: {scenario.expect_verdict}",
            f"    requires_gpu: {str(scenario.requires_gpu).lower()}",
        ]
        if scenario.server_args:
            args = ", ".join(repr(a) for a in scenario.server_args)
            lines.append(f"    server_args: [{args}]")
        if scenario.infra_fault:
            lines.append(f"    infra_fault: {scenario.infra_fault}")
        lines.append("")

    return "\n".join(lines)


@click.command(context_settings={"help_option_names": ["-h", "--help"]})
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_OUT,
    show_default=True,
)
@click.option(
    "--check",
    is_flag=True,
    help="Exit non-zero if the file on disk is stale, instead of rewriting it.",
)
def main(out: Path, check: bool) -> None:
    """Regenerate the vLLM experiment matrix."""
    rendered = render()

    if check:
        if not out.exists():
            raise click.ClickException(f"{out} does not exist; run without --check.")
        if out.read_text() != rendered:
            click.echo(
                f"{out} is stale — the scenario library changed.\n"
                "Regenerate with: python -m rca_engine.scripts.gen_vllm_matrix",
                err=True,
            )
            sys.exit(1)
        click.echo(f"{out} is up to date  ✓")
        return

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered)
    click.echo(f"Wrote {out}")


if __name__ == "__main__":
    main()
